version: '3.7'

services:
  web-flux:
      container_name: web-flux
      image: web-flux:0.1.0
      build: 
        context: . 
        target: develop
      ports:
        - 9887:8080
      tty: true
      working_dir: /webFlux
      volumes:
        - ./:/mvc
     
volumes:
  local:
    
    